<?php

/**
 * BaseAnhang
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $path
 * @property string $name
 * @property integer $anlage_id
 * @property Anlage $Anlage
 * 
 * @method string  getPath()      Returns the current record's "path" value
 * @method string  getName()      Returns the current record's "name" value
 * @method integer getAnlageId()  Returns the current record's "anlage_id" value
 * @method Anlage  getAnlage()    Returns the current record's "Anlage" value
 * @method Anhang  setPath()      Sets the current record's "path" value
 * @method Anhang  setName()      Sets the current record's "name" value
 * @method Anhang  setAnlageId()  Sets the current record's "anlage_id" value
 * @method Anhang  setAnlage()    Sets the current record's "Anlage" value
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnhang extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anhang');
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('anlage_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anlage', array(
             'local' => 'anlage_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}