<?php

/**
 * BaseStunde
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property integer $zim_id
 * @property integer $start_anlage_id
 * @property integer $end_anlage_id
 * @property Anlage $Anlage
 * @property Zim $Zim
 * 
 * @method string  getDescription()     Returns the current record's "description" value
 * @method integer getZimId()           Returns the current record's "zim_id" value
 * @method integer getStartAnlageId()   Returns the current record's "start_anlage_id" value
 * @method integer getEndAnlageId()     Returns the current record's "end_anlage_id" value
 * @method Anlage  getAnlage()          Returns the current record's "Anlage" value
 * @method Zim     getZim()             Returns the current record's "Zim" value
 * @method Stunde  setDescription()     Sets the current record's "description" value
 * @method Stunde  setZimId()           Sets the current record's "zim_id" value
 * @method Stunde  setStartAnlageId()   Sets the current record's "start_anlage_id" value
 * @method Stunde  setEndAnlageId()     Sets the current record's "end_anlage_id" value
 * @method Stunde  setAnlage()          Sets the current record's "Anlage" value
 * @method Stunde  setZim()             Sets the current record's "Zim" value
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStunde extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stunde');
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('zim_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('start_anlage_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('end_anlage_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Anlage', array(
             'local' => 'end_anlage_id',
             'foreign' => 'id'));

        $this->hasOne('Zim', array(
             'local' => 'zim_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}