<?php

/**
 * BaseBild
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $path
 * @property string $caption
 * @property Doctrine_Collection $ZimAnlage
 * 
 * @method string              getPath()      Returns the current record's "path" value
 * @method string              getCaption()   Returns the current record's "caption" value
 * @method Doctrine_Collection getZimAnlage() Returns the current record's "ZimAnlage" collection
 * @method Bild                setPath()      Sets the current record's "path" value
 * @method Bild                setCaption()   Sets the current record's "caption" value
 * @method Bild                setZimAnlage() Sets the current record's "ZimAnlage" collection
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBild extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bild');
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('caption', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ZimAnlage', array(
             'local' => 'id',
             'foreign' => 'bild_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}