<?php

/**
 * BaseStunde
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $lnr
 * @property string $name
 * @property integer $zim_id
 * @property Zim $Zim
 * @property Doctrine_Collection $Anlagen
 * 
 * @method integer             getLnr()     Returns the current record's "lnr" value
 * @method string              getName()    Returns the current record's "name" value
 * @method integer             getZimId()   Returns the current record's "zim_id" value
 * @method Zim                 getZim()     Returns the current record's "Zim" value
 * @method Doctrine_Collection getAnlagen() Returns the current record's "Anlagen" collection
 * @method Stunde              setLnr()     Sets the current record's "lnr" value
 * @method Stunde              setName()    Sets the current record's "name" value
 * @method Stunde              setZimId()   Sets the current record's "zim_id" value
 * @method Stunde              setZim()     Sets the current record's "Zim" value
 * @method Stunde              setAnlagen() Sets the current record's "Anlagen" collection
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStunde extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stunde');
        $this->hasColumn('lnr', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('zim_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('zim_lnr', array(
             'fields' => 
             array(
              0 => 'zim_id',
              1 => 'lnr',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Zim', array(
             'local' => 'zim_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Anlage as Anlagen', array(
             'local' => 'id',
             'foreign' => 'stunde_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}