<?php

/**
 * BaseZim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $ptkuerzel
 * @property string $ptjahr
 * @property integer $user_id
 * @property string $ziele
 * @property string $zielGruppe
 * @property string $roterFaden
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $Stunden
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getPtkuerzel()   Returns the current record's "ptkuerzel" value
 * @method string              getPtjahr()      Returns the current record's "ptjahr" value
 * @method integer             getUserId()      Returns the current record's "user_id" value
 * @method string              getZiele()       Returns the current record's "ziele" value
 * @method string              getZielGruppe()  Returns the current record's "zielGruppe" value
 * @method string              getRoterFaden()  Returns the current record's "roterFaden" value
 * @method sfGuardUser         getSfGuardUser() Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection getStunden()     Returns the current record's "Stunden" collection
 * @method Zim                 setName()        Sets the current record's "name" value
 * @method Zim                 setPtkuerzel()   Sets the current record's "ptkuerzel" value
 * @method Zim                 setPtjahr()      Sets the current record's "ptjahr" value
 * @method Zim                 setUserId()      Sets the current record's "user_id" value
 * @method Zim                 setZiele()       Sets the current record's "ziele" value
 * @method Zim                 setZielGruppe()  Sets the current record's "zielGruppe" value
 * @method Zim                 setRoterFaden()  Sets the current record's "roterFaden" value
 * @method Zim                 setSfGuardUser() Sets the current record's "sfGuardUser" value
 * @method Zim                 setStunden()     Sets the current record's "Stunden" collection
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZim extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zim');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ptkuerzel', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('ptjahr', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('ziele', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('zielGruppe', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('roterFaden', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('Stunde as Stunden', array(
             'local' => 'id',
             'foreign' => 'zim_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}