<?php

/**
 * BaseBild
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $path
 * @property string $caption
 * @property integer $section_id
 * @property Section $Section
 * 
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getPath()       Returns the current record's "path" value
 * @method string  getCaption()    Returns the current record's "caption" value
 * @method integer getSectionId()  Returns the current record's "section_id" value
 * @method Section getSection()    Returns the current record's "Section" value
 * @method Bild    setName()       Sets the current record's "name" value
 * @method Bild    setPath()       Sets the current record's "path" value
 * @method Bild    setCaption()    Sets the current record's "caption" value
 * @method Bild    setSectionId()  Sets the current record's "section_id" value
 * @method Bild    setSection()    Sets the current record's "Section" value
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBild extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bild');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('path', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('caption', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}