<?php

/**
 * BaseZimAnlage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $zeit
 * @property string $ziel
 * @property string $methode
 * @property string $material
 * @property string $tip
 * @property string $kurzinhalt
 * @property string $inhalt
 * @property string $rolle_tm
 * @property integer $bild_id
 * @property Bild $Bild
 * @property Stunde $Stunde
 * 
 * @method string    getName()       Returns the current record's "name" value
 * @method integer   getZeit()       Returns the current record's "zeit" value
 * @method string    getZiel()       Returns the current record's "ziel" value
 * @method string    getMethode()    Returns the current record's "methode" value
 * @method string    getMaterial()   Returns the current record's "material" value
 * @method string    getTip()        Returns the current record's "tip" value
 * @method string    getKurzinhalt() Returns the current record's "kurzinhalt" value
 * @method string    getInhalt()     Returns the current record's "inhalt" value
 * @method string    getRolleTm()    Returns the current record's "rolle_tm" value
 * @method integer   getBildId()     Returns the current record's "bild_id" value
 * @method Bild      getBild()       Returns the current record's "Bild" value
 * @method Stunde    getStunde()     Returns the current record's "Stunde" value
 * @method ZimAnlage setName()       Sets the current record's "name" value
 * @method ZimAnlage setZeit()       Sets the current record's "zeit" value
 * @method ZimAnlage setZiel()       Sets the current record's "ziel" value
 * @method ZimAnlage setMethode()    Sets the current record's "methode" value
 * @method ZimAnlage setMaterial()   Sets the current record's "material" value
 * @method ZimAnlage setTip()        Sets the current record's "tip" value
 * @method ZimAnlage setKurzinhalt() Sets the current record's "kurzinhalt" value
 * @method ZimAnlage setInhalt()     Sets the current record's "inhalt" value
 * @method ZimAnlage setRolleTm()    Sets the current record's "rolle_tm" value
 * @method ZimAnlage setBildId()     Sets the current record's "bild_id" value
 * @method ZimAnlage setBild()       Sets the current record's "Bild" value
 * @method ZimAnlage setStunde()     Sets the current record's "Stunde" value
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZimAnlage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zim_anlage');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('zeit', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('ziel', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('methode', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('material', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('tip', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('kurzinhalt', 'string', 1000, array(
             'type' => 'string',
             'length' => 1000,
             ));
        $this->hasColumn('inhalt', 'string', 10000, array(
             'type' => 'string',
             'length' => 10000,
             ));
        $this->hasColumn('rolle_tm', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('bild_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Bild', array(
             'local' => 'bild_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Stunde', array(
             'local' => 'id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}