<?php

/**
 * BaseStunde
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $description
 * @property integer $zim_id
 * @property Doctrine_Collection $Anlagen
 * @property Zim $Zim
 * 
 * @method string              getDescription() Returns the current record's "description" value
 * @method integer             getZimId()       Returns the current record's "zim_id" value
 * @method Doctrine_Collection getAnlagen()     Returns the current record's "Anlagen" collection
 * @method Zim                 getZim()         Returns the current record's "Zim" value
 * @method Stunde              setDescription() Sets the current record's "description" value
 * @method Stunde              setZimId()       Sets the current record's "zim_id" value
 * @method Stunde              setAnlagen()     Sets the current record's "Anlagen" collection
 * @method Stunde              setZim()         Sets the current record's "Zim" value
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStunde extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stunde');
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('zim_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ZimAnlage as Anlagen', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasOne('Zim', array(
             'local' => 'zim_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}