<?php

/**
 * Anlage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Anlage extends BaseAnlage
{
	public function save(Doctrine_Connection $con = null)
	{  
	
		$conn = $conn ? $conn : $this->getTable()->getConnection();
  		$conn->beginTransaction();
  		try
  		{
 			$ret = parent::save($conn);
 			$this->updateLuceneIndex();
     			$conn->commit();
 
    			return $ret;
  		}
  		catch (Exception $e)
  		{
    			$conn->rollBack();
    			throw $e;
  		}

	}

	public function delete(Doctrine_Connection $conn = null)
	{
  		$index = AnlageTable::getLuceneIndex();
 
  		foreach ($index->find('pk:'.$this->getId()) as $hit)
  		{
    			$index->delete($hit->id);
  		}
 
  		return parent::delete($conn);
	}

	public function updateLuceneIndex()
	{
  		$index = AnlageTable::getLuceneIndex();
 
  		// remove existing entries
  		foreach ($index->find('pk:'.$this->getId()) as $hit)
  		{
    			$index->delete($hit->id);
  		}
 
  		$doc = new Zend_Search_Lucene_Document();
 
  		// store primary key to identify it in the search results
  		$doc->addField(Zend_Search_Lucene_Field::Keyword('pk', $this->getId()));
 
  		// index anlage fields
  		$doc->addField(Zend_Search_Lucene_Field::UnStored('name', $this->getName(), 'utf-8'));
  		$doc->addField(Zend_Search_Lucene_Field::UnStored('ziel', $this->getZiel(), 'utf-8'));
  		$doc->addField(Zend_Search_Lucene_Field::UnStored('inhalt', $this->getInhalt(), 'utf-8'));
 
  		// add anlage to the index
  		$index->addDocument($doc);
  		$index->commit();
	}
}
