<?php

/**
 * Bild
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Bild extends BaseBild
{
	public function save(Doctrine_Connection $conn = null)
	{
		if ( !$this->getPath() ) {
			$this->delete();
		}
		else {
	 		$this->imageScale();
			if ($this->isNew() && !$this->getLnr()){
				$this->setLnr($this->getAnlage()->
					getBilder()->count() + 1);
			}

			$ret = parent::save($conn);
			return $ret;
		}
	}  

	public function delete(Doctrine_Connection $conn = null)
	{
		/// XXX: should be put in transaction, does not work
		$oldLnr = $this->getLnr();			
	  	$ret = parent::delete($conn);
		$this->getTable()->updateLnrDeleted($oldLnr,$this->getAnlage()->getId());
		return $ret;	
	}

	// XXX: not nice, function with side effects, find a better way
	public function generatePathFilename(sfValidatedFile $validatedFile)
	{
		$this->setName($validatedFile->getOriginalName());
		return $validatedFile->generateFilename();
	}	 

	public function imageScale()
	{

		$path = '/'.(sfConfig::get('sf_upload_dir')).'/bilder/'.$this->getPath();

		$filename = $path;
		$image_info = getimagesize($filename);
		$image_type = $image_info[2];
      	
		// Bild laden	
		if( $image_type == IMAGETYPE_JPEG ) {
         		$image = imagecreatefromjpeg($filename);
      		} elseif( $image_type == IMAGETYPE_GIF ) {
         		$image = imagecreatefromgif($filename);
      		} elseif( $image_type == IMAGETYPE_PNG ) {
         		$image = imagecreatefrompng($filename);
      		}

		// Bild Skalieren	        	
      		$height = imagesy($image);
		$width = imagesx($image);
		
		$new_width  = $width;
		$new_height = $height;
		if( $width > 600 ) {
			$ratio = $width / $height;
			$new_width = 600;
			$new_height = $new_width / $ratio;
		}

		$new_image = imagecreatetruecolor($new_width, $new_height);
      		imagecopyresampled($new_image, $image, 0, 0, 0, 0, $new_width, $new_height, $width, $height);
      		$image = $new_image;   
   
		// Bild sichern
	 	if( $image_type == IMAGETYPE_JPEG ) {
                        imagejpeg($image, $filename, 100);
                } elseif( $image_type == IMAGETYPE_GIF ) {
                        imagegif($image, $filename);
                } elseif( $image_type == IMAGETYPE_PNG ) {
                        imagepng($image, $filename);
                }
	}

}
