<?php

/**
 * SectionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SectionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SectionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Section');
    }
    
    public static function getSectionsSorted($anlage_id) {
    	return self::getInstance()->createQuery()->from('Section s')
    	->where('s.anlage_id = ?', $anlage_id)->orderBy('s.lnr')
    	->execute();
    }
    
    public static function updateLnrDeleted($lnr = 0, $anlage_id) {
    	$q = self::getInstance()->createQuery('s')
    	->where('s.anlage_id = ?', $anlage_id)
    	->andWhere('s.lnr > ?', $lnr)->orderBy('s.lnr');
    
    	foreach ($q->execute() as $section) {
    		$section->setLnr($section->getLnr() - 1);
    		$section->save();
    	}
    }
}