<?php

/**
 * Section
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Section extends BaseSection
{
	public function save(Doctrine_Connection $conn = null)
	{
		if ( !$this->getInhalt() && !$this->getTip() ) {
			$this->delete();
		}
		else {
			if ($this->isNew() && !$this->getLnr()){
				$this->setLnr($this->getAnlage()->
						getSections()->count() + 1);
			}
	
			$ret = parent::save($conn);
			$this->getAnlage()->updateLuceneIndex();
			return $ret;
		}
	}
	
	public function delete(Doctrine_Connection $conn = null)
	{
		/// XXX: should be put in transaction, does not work
		$oldLnr = $this->getLnr();
		$ret = parent::delete($conn);
		$this->getTable()->updateLnrDeleted($oldLnr,$this->getAnlage()->getId());
		return $ret;
	}
}
