<?php

/**
 * Stunde
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Stunde extends BaseStunde
{
	public function save(Doctrine_Connection $conn = null)
	{
		if ($this->isNew() && !$this->getLnr()){
			$this->setLnr($this->getZim()->
				getStunden()->count() + 1);
		}
		return parent::save($conn);
	}

	public function __toString()
	{
		return $this->getLnr().'. Stunde: '.$this->getName();
	}
}
