<?php

/**
 * Zim
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Christoph Herbst
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Zim extends BaseZim
{
        public function generateOdf()
	{
		$odf = new odf(dirname(__FILE__).'/../../odftmp/Zim_template.odt');
	//	$stunden = $odf->setSegment('stunden');
		$anlagen = $odf->setSegment('anlagen');
		foreach($this->getStunden() AS $stunde) {
//			$stunden->setVar('nameStunde',$stunde->getName());
			foreach($stunde->getAnlagen() AS $anlage) {
			    $anlagen->name($anlage->getName());
			    $anlagen->zeit($anlage->getZeit());
			    $anlagen->ziel($anlage->getZiel());
			    $anlagen->kurzinhalt($anlage->getKurzinhalt());
			    $anlagen->methode($anlage->getMethode());
			    $anlagen->rolletm($anlage->getRolleTm());
			    $anlagen->material($anlage->getMaterial());
			    $anlagen->merge();
			}
//			$stunden->merge();
		}
//		$odf->mergeSegment($stunden);
		$odf->mergeSegment($anlagen);
		$odf->exportAsAttachedFile ('neuesZim.odt');  
        }
}
