<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    openZIM
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
	public function hasCredential($credential)
	{
		if ( $this->getIsSuperAdmin() ) 
			return true;
		foreach( $this->getGroups() as $group )
			if ( $group->getName() == $credential )
				return true;
		return false;
	}
}
